version: '3'

services:
  blackspots-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'user'
      POSTGRES_USER: 'root'
      POSTGRES_DB: 'blackspots'
    volumes:
      - "db:/var/lib/postgresql"
    ports:
      - "5432:5432"

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true" # Aktiviert das Dashboard ohne HTTPS (nicht empfohlen für Produktionsumgebungen)
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # - "./traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml" # Optional: Für erweiterte Traefik-Konfigurationen
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=hackhpi:$$apr1$$WQA6wnFe$$iLy6O8rMIj.4v7DUyBJ1W."
      - "traefik.http.routers.mein-service.rule=Host(`api.blackspots.de`)"
      - "traefik.http.services.mein-service.loadbalancer.server.port=3000"
      - "traefik.http.services.mein-service.loadbalancer.server.scheme=http"
      - "traefik.http.services.mein-service.loadbalancer.servers[0].url=http://host.docker.internal:3000"

volumes:
  db:

