version: '3'

services:
  blackspots-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'user'
      POSTGRES_USER: 'root'
      POSTGRES_DB: 'blackspots'
    volumes:
      - "db:/var/lib/postgresql"
    ports:
      - "5432:5432"

volumes:
  db:

